---
- name: Add Prometheus HaProxy exporter YUM repositories.
  yum_repository:
    name: "{{ haproxy_exporter_repo_name }}"
    description: "{{ haproxy_exporter_repo_name }} YUM repository"
    file: "{{ haproxy_exporter_repo_name }}"
    baseurl: "{{ haproxy_exporter_repo_url }}"
    gpgcheck: "no"
    timeout: "60"

- name: Install the Prometheus exporter packages.
  yum:
    name: "{{ item.name }}"
    state: "present"
    validate_certs: "no"
    disable_gpg_check: "yes"
  register: haproxy_exporter_yum_status
  until: haproxy_exporter_yum_status is succeeded
  loop:
    - { name: "haproxy_exporter" }
    - { name: "keepalived_exporter", create: haproxy_keepalived_dept | bool }
  retries: 3
  delay: 5

- name: HaProxy exporter configure file transfer.
  template:
    src: "haproxy_exporter.default.j2"
    dest: "/etc/default/haproxy_exporter"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "Ensure haproxy exporter service is enabled."

- name: Keepalived exporter configure file transfer.
  template:
    src: "keepalived_exporter.default.j2"
    dest: "/etc/default/keepalived_exporter"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "Ensure keepalived exporter service is enabled."
