---
- name: Gather HaProxy node variables for HA cluster.
  set_fact:
    haproxy_servers: "\
      {% set _haproxy_servers = [] %}\
      {% for host in groups[group_names[0]] %}\
      {% if _haproxy_servers.append(hostvars[host]['ansible_host']) %}{% endif %}\
      {% endfor %}\
      {{ _haproxy_servers }}"
  when: haproxy_servers is not defined or haproxy_servers | length < 1

- name: Include tasks for specific OS.
  ansible.builtin.include_tasks: "{{ ansible_distribution_file_variety }}.yml"

- name: Straight to getenforce selinux status.
  ansible.builtin.include_tasks: "selinux.yml"

- name: Include firewall tasks.
  ansible.builtin.include_tasks: "firewall.yml"

- name: Include configuration tasks.
  ansible.builtin.include_tasks: "configureation.yml"

- name: Include KeepAlived tasks.
  ansible.builtin.include_tasks: "keepalived.yml"
  when: haproxy_keepalived_dept | bool

- name: Include prometheus exporter tasks.
  ansible.builtin.include_tasks: "exporter.yml"

- name: Include service mesh tasks.
  ansible.builtin.include_tasks: "register.yml"
  when:
    - exporter_is_install | bool
    - consul_public_register | bool

- name: Force the handler to run immediately.
  meta: flush_handlers
