---
- name: Enable HaProxy service.
  systemd:
    name: "haproxy.service"
    enabled: "yes"
    state: "restarted"
    daemon_reload: "yes"
  listen: Ensure haproxy service is enabled.

- name: Enable Keepalived service.
  systemd:
    name: "keepalived.service"
    enabled: "yes"
    state: "restarted"
    daemon_reload: "yes"
  listen: Ensure keepalived service is enabled.

- name: Enable HaProxy exporter service.
  systemd:
    name: "haproxy_exporter.service"
    enabled: "yes"
    state: "restarted"
    daemon_reload: "yes"
  listen: Ensure haproxy exporter service is enabled.

- name: Enable Keepalived exporter service.
  systemd:
    name: "keepalived_exporter.service"
    enabled: "yes"
    state: "restarted"
    daemon_reload: "yes"
  listen: Ensure keepalived exporter service is enabled.
